### ISSUE TITLE
Trouble on disable buttons

### ISSUE THREAD

**Issue by xMase** [TwanoO67/ngx-admin-lte#11]
Header buttons cant be disabled, on auth.ts change:

`this.skin = param['skin'] ? param['skin'] : 'skin-blue';
        this.display_control = param['display_control'] ? param['display_control'] : true;
        this.display_user = param['display_user'] ? param['display_user'] : true;
        this.display_tasks = param['display_tasks'] ? param['display_tasks'] : true;
        this.display_messages = param['display_messages'] ? param['display_messages'] : true;
this.display_notifications = param['display_notifications'] ? param['display_notifications'] : true;`

to
`        this.skin = !isNullOrUndefined(param['skin']) ? param['skin'] : 'skin-blue';
        this.display_control = !isNullOrUndefined(param['display_control']) ? param['display_control'] : true;
        this.display_user = !isNullOrUndefined(param['display_user']) ? param['display_user'] : true;
        this.display_tasks = !isNullOrUndefined(param['display_tasks']) ? param['display_tasks'] : true;
        this.display_messages = !isNullOrUndefined(param['display_messages']) ? param['display_messages'] : true;
        this.display_notifications = !isNullOrUndefined(param['display_notifications']) ? param['display_notifications'] : true;`

**Comment by TwanoO67** [comment]
Thanks for the report will try it later and use that for the 0.6.0

**Comment by catull** [comment]
Another approach would be:

```javascript
this.skin = !!param['skin'] ? param['skin'] : 'skin-blue';
this.display_control = !!param['display_control'] ? param['display_control'] : true;
this.display_user = !!param['display_user'] ? param['display_user'] : true;
this.display_tasks = !!param['display_tasks'] ? param['display_tasks'] : true;
this.display_messages = !!param['display_messages'] ? param['display_messages'] : true;
this.display_notifications = !!param['display_notifications'] ? param['display_notifications'] : true;
```

**Comment by TwanoO67** [comment]
@xMase those should be fixed by 0.6.2 version.
Can you confirm ?

**Comment by catull** [comment]
Thanks for looking into this.

Your fix does not work, yet.
I still see the notifications and messages etc.

This line https://github.com/TwanoO67/ngx-admin-lte/blob/develop/src/layouts/auth/auth.ts#L55 must be

```javascript
   return param.hasOwnProperty(index) ? param[index] : defaut;
```

With this fix, the params I hand in are honoured.

Here's the reason.

I have this code snippet:

```json
    component: LayoutAuthComponent,
    data: [{
      'skin': 'skin-blue',
      'display_control': false,
      'display_messages': false,
      'display_notifications': false,
      'display_tasks': false,
      'display_user': true
    }],
 ```
Then Line 55 of the code does this, for the case of `'display_control'`:

param['display_control'] is true, because the property 'display_control' is defined in the param structure.

Consequently, !!param[''display_control'] is false, so the default is taken, which is true.

By the way, **default** is spelled that way, not **defaut**.
It is "défaut" in French, though.

Please consider this small change.
I debugged it and it works.

**Comment by TwanoO67** [comment]
Ok, change had been made.
Please try with the 0.6.3 version

**Comment by catull** [comment]
Excellent work, works as desired.
You can close this issue now.
