### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by catull** [TwanoO67/ngx-admin-lte#30]
There is currently no support for Angular 5.

I dabbled a bit, have a somehow working solution.
BUT, I had to completely switch off the translation functionality.

See for inspiration [@catull/ngx-admin-lte/tree/no-translation](https://github.com/catull/ngx-admin-lte/tree/no-translation).

**Comment by fabioformosa** [comment]
So doesn't it support i18n?

**Comment by TwanoO67** [comment]
Hello guys,

To achieve that i need help on issue #47 
If you have any idea it would be much appreciated

**Comment by TwanoO67** [comment]
seems fixed by 2.0.0.beta-7
Can you confirm ?

**Comment by catull** [comment]
Not quite fixed yet.

With 2.0.0.beta-7 I get

ERROR in : Unexpected value 'undefined' declared by the module 'NgxAdminLteModule in node_modules/ngx-admin-lte/ngx-admin-lte.d.ts'

I did not see this error in 1.x before.

**Comment by catull** [comment]
Hang on, seems to be an angular build problem.

This build statement causes the error: `ng build --environment prod --build-optimizer --aot`.
This build statement succeeds: `ng build --environment prod`.

Will open an issue against NG cli: https://github.com/angular/angular-cli/issues/9923

**Comment by catull** [comment]
This is now implemented with 2.0.0-beta.9.
